behaviors:
  RobotAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960          # typically 20× batch_size or higher
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.01                  # entropy regularization
      epsilon: 0.2                # clipping parameter
      lambd: 0.95                 # GAE lambda
      num_epoch: 3                # PPO epochs per update
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 30000
    threaded: false
